# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39cd43fa79b8e4e81fcf72f2d2bdb3006a0738e2d29e1c03f351c7cba1df542ef8cfec027fb37a8cbe38399734f50e87ab8b31b822b839ba217e7a9755446059

test:
  secret_key_base: d814de099a33aa1804e7963f784d7320299600e316263a37eb527377c53edef47bb5625a0984591ea23e7b9b817be6be7100e0b0f49ee7d08f18493504533fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
